name: ea-python
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip
  # Core scientific python
  - numpy
  - matplotlib
  - pyqt
  - seaborn
  - tqdm
  - kiwisolver

  # Spatial package
  - pysal
  - pyproj
  - rasterstats
  - geopy
  - cartopy
  - descartes
  - contextily
  - earthpy>=0.9.2
  - folium
  - geojson
  - mapboxgl
  - hydrofunctions
  - geocoder
  - tweepy
  - xarray
  - rioxarray
  - scipy
  - netcdf4
  - nc-time-axis
  - regionmask

  # Natural language processing
  - nltk
  - textblob

  # Jupyter Environment
  - papermill
  - autopep8
  - notebook
  - ipython
  - nbclean
  - nbresuse
  # Autograding
  - matplotcheck>=0.1.2
  - nbgrader
